### ISSUE TITLE
Issue on jsonPath filter

### ISSUE THREAD

**Issue by yyoussouf** [jsurfer/JsonSurfer#29]
Hello,

Given this json : 

```
{
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95,
                "description":{
                       "year":"2000"
                 }
            },
            {
                "category": "fiction",
                "author": "Evelyn Waugh",
                "title": "Sword of Honour",
                "price": 12.99,
                "description":{
                       "year":"2010"
                 }
            },
            {
                "category": "fiction",
                "author": "Herman Melville",
                "title": "Moby Dick",
                "isbn": "0-553-21311-3",
                "price": 8.99,
                "description":{
                       "year":"2000"
                 }
            },
            {
                "category": "fiction",
                "author": "J. R. R. Tolkien",
                "title": "The Lord of the Rings",
                "isbn": "0-395-19395-8",
                "price": 22.99
            }
        ],
        "bicycle": {
            "color": "red",
            "price": 19.95
        }
    },
    "expensive": 10
}
```

The path  **$.store.book[?(@.description.year=='2010')]**

  should return : 

```
{
    "category": "fiction",
    "author": "Evelyn Waugh",
    "title": "Sword of Honour",
    "price": 12.99,
    "description":{
            "year":"2010"
    }
}
```

But when I execute this code : 
```
JsonSurfer surfer = JsonSurferJackson.INSTANCE;
Object actualValue = surfer.collectOne(json, "$.store.book[?(@.description.year=='2010')]");
```

I get this exception : 
```
org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:66)
	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at org.jsfr.json.compiler.JsonPathParser.filter(JsonPathParser.java:726)
	at org.jsfr.json.compiler.JsonPathParser.path(JsonPathParser.java:260)
	at org.jsfr.json.compiler.JsonPathCompiler.compile(JsonPathCompiler.java:220)
	at org.jsfr.json.SurfingConfiguration$Builder.bind(SurfingConfiguration.java:131)
	at org.jsfr.json.JsonSurferTest.testJsonPathFilterDeep(JsonSurferTest.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:61)
	... 29 more
```

**Comment by wanglingsong** [comment]
This bug was reported at #28 and fixed in the master branch already. I will make a release 1.4.1 soon.
Thanks for the reminder!

**Comment by wanglingsong** [comment]
HI, @yyoussouf, 1.4.1 was released. Please feel free to test it.
